default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  user: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'postgres' } %>

development:
  <<: *default
  database: bycoders_development

test:
  <<: *default
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  database: bycoders_development_test<%= ENV['TEST_ENV_NUMBER'] %>
  password: postgres

production: &production
  url:  <%= ENV["RDS_DATABASE_URL"] || ENV["DATABASE_URL"] %>
  pool: <%= ENV["RDS_DB_POOL"] || ENV['MAX_THREADS'] || 5 %>